<?php

namespace App\Helpers;

class HusnaHelper
{
    public static function getNames()
    {
        return [
            ['name' => 'Al-Rahman', 'meaning' => 'Hamma uchun mehribon'],
            ['name' => 'Al-Rahim', 'meaning' => 'O\'ta rahm-shafqatli'],
            ['name' => 'Al-Malik', 'meaning' => 'Hamma narsaning egasi'],
            ['name' => 'Al-Quddus', 'meaning' => 'Barcha aybu nuqsonlardan pok'],
            ['name' => 'As-Salam', 'meaning' => 'Tinchlik-omonlik beruvchi'],
            ['name' => 'Al-Mu’min', 'meaning' => 'Imon va omonlik beruvchi'],
            ['name' => 'Al-Muhaymin', 'meaning' => 'Barchasini kuzatib turuvchi'],
            ['name' => 'Al-Aziz', 'meaning' => 'G\'olib va qudratli'],
            ['name' => 'Al-Jabbar', 'meaning' => 'O\'zi xohlaganini majburan qildiruvchi'],
            ['name' => 'Al-Mutakabbir', 'meaning' => 'Kibru va kibriyo egasi'],
            ['name' => 'Al-Xaliq', 'meaning' => 'Yaratuvchi'],
            ['name' => 'Al-Bari', 'meaning' => 'Yaratuvchi (nuqsonsiz)'],
            ['name' => 'Al-Musavvir', 'meaning' => 'Barcha narsaga surati va shakl beruvchi'],
            ['name' => 'Al-Gaffar', 'meaning' => 'Gunohlarni ko\'plab kechiruvchi'],
            ['name' => 'Al-Qahhar', 'meaning' => 'Barchani bo\'ysundiruvchi'],
            ['name' => 'Al-Vahhab', 'meaning' => 'Ne\'matlarni tekinga beruvchi'],
            ['name' => 'Ar-Razzaq', 'meaning' => 'Rizq beruvchi'],
            ['name' => 'Al-Fattah', 'meaning' => 'Eshiklarni ochuvchi, g\'alaba beruvchi'],
            ['name' => 'Al-Alim', 'meaning' => 'Barchasini biluvchi'],
            ['name' => 'Al-Qabiz', 'meaning' => 'Rizqlarni tor qiluvchi, jonlarni oluvchi'],
            ['name' => 'Al-Basit', 'meaning' => 'Rizqlarni keng qiluvchi, jonlar beruvchi'],
            ['name' => 'Al-Xafiz', 'meaning' => 'Pastlatuvchi (kofirlarni)'],
            ['name' => 'Ar-Rafi', 'meaning' => 'Ko\'taruvchi (mo\'minlarni)'],
            ['name' => 'Al-Muizz', 'meaning' => 'Aziz qiluvchi'],
            ['name' => 'Al-Muzill', 'meaning' => 'Xor qiluvchi'],
            ['name' => 'As-Sami', 'meaning' => 'Eshituvchi'],
            ['name' => 'Al-Basir', 'meaning' => 'Ko\'ruvchi'],
            ['name' => 'Al-Hakam', 'meaning' => 'Hukm qiluvchi'],
            ['name' => 'Al-Adl', 'meaning' => 'O\'ta adolatli'],
            ['name' => 'Al-Latif', 'meaning' => 'Lutf qiluvchi, daqiq ishlarni ham biluvchi'],
            ['name' => 'Al-Xabir', 'meaning' => 'Xabardor'],
            ['name' => 'Al-Halim', 'meaning' => 'G\'azabi kelmaydigan, muloyim'],
            ['name' => 'Al-Azim', 'meaning' => 'Buyuk'],
            ['name' => 'Al-Gafur', 'meaning' => 'Kechiruvchi'],
            ['name' => 'Ash-Shakur', 'meaning' => 'Oz amal uchun ko\'p mukofot beruvchi'],
            ['name' => 'Al-Aliy', 'meaning' => 'Oliydan oliy'],
            ['name' => 'Al-Kabir', 'meaning' => 'Katta, ulug\''],
            ['name' => 'Al-Hafiz', 'meaning' => 'Saqlovchi'],
            ['name' => 'Al-Muqit', 'meaning' => 'Moddiy va ma’naviy rizq beruvchi'],
            ['name' => 'Al-Hasib', 'meaning' => 'Kifoya qiluvchi, hisob-kitob qiluvchi'],
            ['name' => 'Al-Jalil', 'meaning' => 'Ulug\'vor'],
            ['name' => 'Al-Karim', 'meaning' => 'Saxovatli'],
            ['name' => 'Ar-Raqib', 'meaning' => 'Kuzatib turuvchi'],
            ['name' => 'Al-Mujib', 'meaning' => 'Duolarni ijobat qiluvchi'],
            ['name' => 'Al-Vasi', 'meaning' => 'Keng qamrovli'],
            ['name' => 'Al-Hakim', 'meaning' => 'Hikmatli'],
            ['name' => 'Al-Vadud', 'meaning' => 'Sevuvchi'],
            ['name' => 'Al-Majid', 'meaning' => 'Shon-sharafli'],
            ['name' => 'Al-Ba’is', 'meaning' => 'Qayta tiriltiruvchi'],
            ['name' => 'Ash-Shahid', 'meaning' => 'Guvoh'],
            ['name' => 'Al-Haqq', 'meaning' => 'Haqiqat'],
            ['name' => 'Al-Vakil', 'meaning' => 'Vakil, o\'z zimmasiga oluvchi'],
            ['name' => 'Al-Qaviy', 'meaning' => 'Kuchli'],
            ['name' => 'Al-Matin', 'meaning' => 'Mustahkam, baquvvat'],
            ['name' => 'Al-Valiy', 'meaning' => 'Do\'st va yordamchi'],
            ['name' => 'Al-Hamid', 'meaning' => 'Hamdga loyiq'],
            ['name' => 'Al-Muhsi', 'meaning' => 'Barchasini hisoblab turuvchi'],
            ['name' => 'Al-Mubdi', 'meaning' => 'Boshlab beruvchi'],
            ['name' => 'Al-Muid', 'meaning' => 'Qaytaruvchi'],
            ['name' => 'Al-Muhyi', 'meaning' => 'Tiriltiruvchi'],
            ['name' => 'Al-Mumit', 'meaning' => 'O\'ldiruvchi'],
            ['name' => 'Al-Hayy', 'meaning' => 'Tirik'],
            ['name' => 'Al-Qayyum', 'meaning' => 'O\'z-o\'zidan turuvchi, boshqalarni tutib turuvchi'],
            ['name' => 'Al-Vajid', 'meaning' => 'Topuvchi'],
            ['name' => 'Al-Majid', 'meaning' => 'Ulug\'vor (faqat Allohga xos)'],
            ['name' => 'Al-Vahid', 'meaning' => 'Yagona'],
            ['name' => 'Al-Ahad', 'meaning' => 'Yagona (zoti va sifatlarida)'],
            ['name' => 'As-Samad', 'meaning' => 'Ehtiyojsiz, hamma Unga muhtoj'],
            ['name' => 'Al-Qadir', 'meaning' => 'Qodir'],
            ['name' => 'Al-Muqtadir', 'meaning' => 'O\'ta qudratli'],
            ['name' => 'Al-Muqaddim', 'meaning' => 'Oldinga suruvchi'],
            ['name' => 'Al-Muaxxir', 'meaning' => 'Orqaga suruvchi'],
            ['name' => 'Al-Avval', 'meaning' => 'Birinchi'],
            ['name' => 'Al-Axir', 'meaning' => 'Oxirgi'],
            ['name' => 'Az-Zahir', 'meaning' => 'Ochiq-oydin'],
            ['name' => 'Al-Batin', 'meaning' => 'Maxfiy'],
            ['name' => 'Al-Vali', 'meaning' => 'Egalik qiluvchi'],
            ['name' => 'Al-Muta’ali', 'meaning' => 'Oliydan oliy'],
            ['name' => 'Al-Barr', 'meaning' => 'Yaxshilik qiluvchi'],
            ['name' => 'At-Tavvab', 'meaning' => ' Tavbalarni qabul qiluvchi'],
            ['name' => 'Al-Muntaqim', 'meaning' => 'O\'ch oluvchi (adolat bilan)'],
            ['name' => 'Al-Afuvv', 'meaning' => 'Afv etuvchi'],
            ['name' => 'Ar-Rauf', 'meaning' => 'Mehribon'],
            ['name' => 'Malik-ul-Mulk', 'meaning' => 'Mulk egasi'],
            ['name' => 'Zul-Jalali val Ikrom', 'meaning' => 'Ulug\'lik va ikrom egasi'],
            ['name' => 'Al-Muqsit', 'meaning' => 'Adolatli tarqatuvchi'],
            ['name' => 'Al-Jami', 'meaning' => 'To\'plovchi'],
            ['name' => 'Al-Ganiy', 'meaning' => 'Boy, ehtiyojsiz'],
            ['name' => 'Al-Mugni', 'meaning' => 'Boy qiluvchi'],
            ['name' => 'Al-Mani', 'meaning' => 'To\'suvchi, himoya qiluvchi'],
            ['name' => 'Ad-Darr', 'meaning' => 'Zarar beruvchi (sinov uchun)'],
            ['name' => 'An-Nafi', 'meaning' => 'Foyda beruvchi'],
            ['name' => 'An-Nur', 'meaning' => 'Nur taratuvchi'],
            ['name' => 'Al-Hadi', 'meaning' => 'Hidoyat beruvchi'],
            ['name' => 'Al-Badi', 'meaning' => 'Mislsiz yaratuvchi'],
            ['name' => 'Al-Baqi', 'meaning' => 'Boqiy, abadiy'],
            ['name' => 'Al-Varis', 'meaning' => 'Merosxo\'r (hamma ketgach qoluvchi)'],
            ['name' => 'Ar-Rashid', 'meaning' => 'To\'g\'ri yo\'lga boshlovchi'],
            ['name' => 'As-Sabur', 'meaning' => 'Sabrli'],
        ];
    }

    public static function getName(int $index)
    {
        $names = self::getNames();
        return $names[$index % count($names)];
    }
}
